doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_mysql'
        charset: utf8mb4
        server_version: '9.1.0' # Ajuste à ta version de MySQL
        schema_filter: ~^(?!sys|information_schema)~
        types:
            enum: Doctrine\DBAL\Types\StringType
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
            App:   # Par défaut, toutes les entités dans src/Entity
                is_bundle: false
                type: annotation # ou attribute selon ce que tu utilises
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
