lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    # token_ttl: 86400 # 1 day in seconds
    token_ttl: 14400


    # api_platform:
    #     check_path: /api/login_check
    #     username_path: email_address
    #     password_path: password